/*
Navicat MySQL Data Transfer

Source Server         : Server
Source Server Version : 50527
Source Host           : localhost:3306
Source Database       : world

Target Server Type    : MYSQL
Target Server Version : 50527
File Encoding         : 65001

Date: 2013-08-04 19:34:50
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `command`
-- ----------------------------
DROP TABLE IF EXISTS `command`;
CREATE TABLE `command` (
  `name` varchar(50) NOT NULL DEFAULT '',
  `security` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `help` longtext,
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Chat System';

-- ----------------------------
-- Records of command
-- ----------------------------
INSERT INTO `command` VALUES ('account create', '4', 'Syntax: .account create $account $password\\n creates an account with the specified password. \');');
INSERT INTO `command` VALUES ('account delete', '4', 'Syntax : .account delete account with $account\\n deletes all characters. \');');
INSERT INTO `command` VALUES ('account lock', '4', 'Syntax: .account lock on|off] \\n allowed login for this account only from the current IP (on) or removes the limit (off) . \');');
INSERT INTO `command` VALUES ('account onlinelist', '4', 'Syntax: .account onlinelist\\n shows a list of all the currently active acccounts. \');');
INSERT INTO `command` VALUES ('account password', '4', 'Syntax: .account password $altes_passwort $neues_passwort $neues_passwort\\n changes the password for your account, your new password must be entered for security reasons 2x. \');');
INSERT INTO `command` VALUES ('account set addon', '4', 'Syntax: .account set addon [ $account] $addon\\n allows the Account $account (or the selected character) the use of the extensions. Possible values: 0 - normal 1 - tbc, 2 - wotlk. \');');
INSERT INTO `command` VALUES ('account set gmlevel', '4', 'Syntax: .account set gmlevel [ $account] $level [ $realmid] \\n sets the GM-level of the selected player (can not be used on itself) or for account $account on level $level for the realm with ID $realmid. \\n$level can range from 0 to 3. $Relamid = -1 for all realms. \');');
INSERT INTO `command` VALUES ('account set password', '4', 'Syntax: .account set password $account $new_password $new_password\\n changes the password for the Account $account. \');');
INSERT INTO `command` VALUES ('account set', '4', 'Syntax: .account set $subcommand\\n .account set for a list of subcommands or .help account set $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('account', '1', 'Syntax: .account\\n indicates the authorization level your account. \');');
INSERT INTO `command` VALUES ('additem', '3', 'Syntax: .additem $Itemid/ [ $itemname] / $shift-click-item-link $itemcount] \\n Adds 1 or $itemcount Number of Items id $Itemid (or more exactly ( !) name $ITEMNAME has been added in brackets, or with shift-click generated link of a items from the inventory or recipe) to your or the inventory of the selected character. A negative value for $itemcount removes the specified number. \');');
INSERT INTO `command` VALUES ('additemset', '3', 'Syntax: .additemset $itemsetid\\n adds items to a together into together into itemsets id $itemsetid your or the inventory of the selected character. Each part of the together into together into itemsets will be added once. \');');
INSERT INTO `command` VALUES ('announce', '2', 'Syntax: .announce $MessageToBroadcast\\n sends a notification to all players in the chat window. \');');
INSERT INTO `command` VALUES ('aura', '4', 'Syntax: .aura $spellid\\n adds the aura of the spells $spellid of the selected unit. \');');
INSERT INTO `command` VALUES ('ban account', '4', 'Syntax: .ban account $name $bantime $reason\\n Ban account kick player. \\n $bantime: A negative number causes a continuous spell, otherwise use a format such as \\ \" 4D20h3s\\ \' . \');');
INSERT INTO `command` VALUES ('ban character', '4', 'Syntax: .ban character $name $bantime $reason\\n Ban account and kick player. \\n$bantime: A negative number causes a permanent ban, otherwise use a format such as \\ \" 4D20h3s\\ \' . \');');
INSERT INTO `command` VALUES ('ban ip', '4', 'Syntax: .ban ip $IP $bantime $reason\\reqapt for additional time IP. \\n $Bantime: A negaive number causes a continuous spell, otherwise use a format such as \\ \" 4D20h3s\\ \' . \');');
INSERT INTO `command` VALUES ('ban', '4', 'Syntax: .ban $subcommand\\n .ban for a list of subcommands or .help ban $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('baninfo account', '2', 'Syntax: .baninfo account\\n shows you the full information about a particular spell. \');');
INSERT INTO `command` VALUES ('baninfo character', '2', 'Syntax: .baninfo character\\n shows you the full information about a particular spell. \');');
INSERT INTO `command` VALUES ('baninfo ip', '2', 'Syntax: .baninfo IP\\n shows you the full information about a particular spell. \');');
INSERT INTO `command` VALUES ('baninfo ', '2', 'Syntax: .baninfo $subcommand\\n .baninfo for a list of subcommands or .help baninfo $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('bank', '4', 'Syntax: .bank\\n opens the bank loose. \');');
INSERT INTO `command` VALUES ('banlist account', '4', 'Syntax: .banlist account [ $name \\n looks in the ban list after an account name with a specified pattern or shows all devoted things Accounts. \' ) ;');
INSERT INTO `command` VALUES ('banlist character', '4', 'Syntax: .banlist  Character $name\\n searches in the ban list after a character name with a specific pattern. Setting a pattern. \');');
INSERT INTO `command` VALUES ('banlist ip', '4', 'Syntax: .banlist IP ( $IP. \\N looks in the ban list after an IP with a specified pattern or shows all devoted things IPs. \');');
INSERT INTO `command` VALUES ('banlist', '4', 'Syntax: .banlist $subcommand\\n .banlist for a list of subcommands or .help banlist $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('bindsight', '4', 'Syntax: .bindsight\\n provides for a selected unit from the point of view for an indefinite period of time. Cannot be used while your controlled another destination. \');');
INSERT INTO `command` VALUES ('cast back', '4', 'Syntax: .cast back $spellid [triggered] \\n the selected target leads the magic $spellid on your character. If \\ \'triggered\\\' or a part of it has been specified, the spell will run with a triggered flag. \');');
INSERT INTO `command` VALUES ('cast dist', '4', 'Syntax: .cast dist $spellid [ $dist [triggered] ] \\n applies the Magic on a point in the distance $dist. If \\ \'trigered\\\' or only a part is specified, then the spell will worked with triggered flag. Not all spells can be worked as a Distanzzauber. \');');
INSERT INTO `command` VALUES ('cast self', '4', 'Syntax: .cast self $spellid [triggered] \\n the selected target leads the magic $spellid on itself. If \\ \'triggered\\\' or a part of it has been specified, the spell will run with a triggered flag. \');');
INSERT INTO `command` VALUES ('cast target', '4', 'Syntax: .cast target $spellid [triggered] \\n the selected target will be the magic $spellid on target. If \\ \'triggered\\\' or a part of it has been specified, the spell will run with a triggered flag. \');');
INSERT INTO `command` VALUES ('cast', '4', 'Syntax: .cast $spellid [triggered] \\n $spellid is executed on the selected target. If no target is selected, the spell will run on you. If \\ \'triggered\\\' or a part of it has been specified, the spell will run with a triggered flag. \');');
INSERT INTO `command` VALUES ('character customize', '4', 'Syntax: .character customize $name \\n the selected char or Char $name can be transformed into the next logon. \');');
INSERT INTO `command` VALUES ('character erase', '4', 'Syntax: .character erase $name\\n the Char $name will be permanently deleted, regardless of any time delete options. \');');
INSERT INTO `command` VALUES ('character level', '4', 'Syntax: .character level [ $name $level \\n The level of the selected char or Char $name is by the amount $level or to +1 changed. \');');
INSERT INTO `command` VALUES ('character rename', '3', 'Syntax: .character rename [ $name \\n The selected char or Char $name must be renamed the next logon. \');');
INSERT INTO `command` VALUES ('character reputation', '4', 'Syntax: .character reputation [ $name \\n shows the call of the selected char or Char $name. \');');
INSERT INTO `command` VALUES ('combatstop', '2', 'Syntax: .combatstop [ $name \\n keeps the melee of the selected char Or Char $name. If no player is selected, the command is acted upon you. \');');
INSERT INTO `command` VALUES ('cometome', '4', 'Syntax: .cometome $name\\n calls the player $name. The new position will not be stored in the DB \');');
INSERT INTO `command` VALUES ('commands', '0', 'Syntax: .commands\\n shows the commands of their authorization level. \');');
INSERT INTO `command` VALUES ('cooldown', '2', 'Syntax: .cooldown [ $spell_id] \\n Removes all (if not specified) or only the spell_id Cooldown of $spell_id from the selected character or of them (if nobody selected) . \');');
INSERT INTO `command` VALUES ('damage', '4', 'Syntax: .damage $damage_amount [ $school [ $spellid] ] \\n adds the goal of $damage Damage to. If $school and $spellid was not specified, then normal melee damage without any modifications. If the damage is $school what specified with Rustungsreduzierung modified (if school physical is), and the destination, the modification and absorb the result as a melee damager worked on the objective. If spell has been specified, the damage as Zauberschaden mofiziert and worked. Can be used as Shift-Link $spellid. \');');
INSERT INTO `command` VALUES ('debug arena', '4', 'Syntax: .debug arena\\n changes the debug mode for the arenas. In debug mode the Arena a GM can start with individual players. \');');
INSERT INTO `command` VALUES ('debug bg', '4', 'Syntax: .debug bg\\n changes the debug mode for the BG Network Connections. In debug mode the BGS a GM can start with individual players. \');');
INSERT INTO `command` VALUES ('debug Mod32Value', '4', 'Syntax: .debug Mod32Value $field $value\\n adds the value $value to the field $field of the own chars. \');');
INSERT INTO `command` VALUES ('debug play cinematic', '4', 'Syntax: .debug Play cinematic $cinematic\\n plays the Animation $cinematic. The Char remains in place, while the Spirit flies. \');');
INSERT INTO `command` VALUES ('debug play movie', '4', 'Syntax: .debug $movie play movie\\n plays the film $movie. \');');
INSERT INTO `command` VALUES ('debug play sound', '4', 'Syntax: .debug Play sound $soundid\\n the music plays with $soundid. \\nthe music is played only for you. Other players will not hear this. \\Nvorsicht: The client knows more than 5000 music ... \');');
INSERT INTO `command` VALUES ('debug', '4', 'Syntax: .debug $subcommand\\n .debug for a list of the subcommands or .help debug $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('demorph', '1', 'Syntax: .demorph\\n is the selected player his original appearance. \');');
INSERT INTO `command` VALUES ('die', '4', 'Syntax: .The\\n kills the selected player. If no player is selected, the command is kill you. \');');
INSERT INTO `command` VALUES ('dismount', '0', 'Syntax: .dismount\\n dismounted you if your mounted. \');');
INSERT INTO `command` VALUES ('distance', '3', 'Syntax: .distance\\n shows the distance to the selected creature. \');');
INSERT INTO `command` VALUES ('event activelist', '4', 'Syntax: .event activelist\\n Displays a list of the current active events. \');');
INSERT INTO `command` VALUES ('event start', '3', 'Syntax: .event start $event_sys id\\n starts the Event $event_sys id. Sets the start time of the event to the present moment (the change is not in the DB stored) . \');');
INSERT INTO `command` VALUES ('event stop', '3', 'Syntax: .event stop $event_sys id\\n stops the Event $event_sys id. Sets the start time of the event to a time in the past, the present moment is the end time of the event (the change is not in the DB stored) . \');');
INSERT INTO `command` VALUES ('event', '2', 'Syntax: .event $event_sys id\\n shows the details of the Event with $event_sys id. \');');
INSERT INTO `command` VALUES ('cheat cooldown', '4', 'Syntax: .cheat cooldown on/off \\r\\nEnables or disables your character\\\'s spell cooldowns. \');');
INSERT INTO `command` VALUES ('cheat power', '4', 'Syntax: .cheat power on/off \\r\\nEnables or disables your character\\\'s spell cost (foer mana) . \');');
INSERT INTO `command` VALUES ('freeze', '1', 'Syntax: .freeze [ $name. \\n the selected char or Char $name is frozen and his Chat locked. \');');
INSERT INTO `command` VALUES ('gm chat', '1', 'Syntax: .gm chat on/off \\n Enables or disables the Chat GM Mode (display the GM-characters in the messages) or display the current status (On/Off) . \');');
INSERT INTO `command` VALUES ('gm fly', '1', 'Syntax: .gm fly on/off \\n Enables/disables the GM airplane mode or display the current status. \');');
INSERT INTO `command` VALUES ('gm ingame', '1', 'Syntax: .gm ingame\\n shows all available gamemasters. \');');
INSERT INTO `command` VALUES ('gm list', '1', 'Syntax: .gm list\\n Displays a list of all gamemasters and your access privileges. \');');
INSERT INTO `command` VALUES ('gm visible', '1', 'Syntax: .gm visible on/off \\n makes the GM visible(on) or invisible(off) for other players or showed the current status. \');');
INSERT INTO `command` VALUES ('gm ', '1', 'Syntax: .gm on/off \\n activated or deactivated in the game the GM mode or display the current status (On/Off) . \');');
INSERT INTO `command` VALUES ('gmannounce', '1', 'syntax: .Gmannounce $announcement\\n sends to announcement To gamemasters Are online. \');');
INSERT INTO `command` VALUES ('gmnameannounce', '1', 'Syntax: .gmnameannounce $announcement. \\N sends to announcement to all online GM\\ \'s.  Name of the sender is displayed. \');');
INSERT INTO `command` VALUES ('gmnotify', '1', 'Syntax: .gmnotify $notification\\n Displays a message on the screen of all online GM\\ \'s . \');');
INSERT INTO `command` VALUES ('go creature', '3', 'Syntax: .go creature $creature_guid teleport your character\\n to the creature with GUID $creature_guid. \\n\\n.go creature $creature_name teleported to the NPC your character with the name $creature_name. \\N.go creature id $creature_id\\n teleported to a NPC your character from the template with this entry spawns. \\N * if * More than to NPC wants to be found, so you will first of all, the is found in the database, teleported. \');');
INSERT INTO `command` VALUES ('go graveyard', '3', 'Syntax: .go graveyard $graveyardId\\n teleported you to the cemetery with the specified graveyardId. \');');
INSERT INTO `command` VALUES ('go grid', '4', 'syntax: .Go grid $gridX gridY $ [ $mapid] \\n teleported you to the center of the grid on the map with the specified indices $mapid (or the current map if no mapid what specified) . \');');
INSERT INTO `command` VALUES ('go object', '4', 'Syntax: .go object $object_guid\\n teleported you to the Gameobject with the GUID $object_guid\');');
INSERT INTO `command` VALUES ('go taxinode', '4', 'Syntax: .go taxinode $taxinode teleport the player to Flugmeister\\n/berth $taxinode. List of valid destinations can be retrieved with the .lookup taxinode. \');');
INSERT INTO `command` VALUES ('go ticket', '2', 'Syntax: .go ticket, $teleported ticktid\\n the player at the point at which the Ticket $ticket ID has been created. \');');
INSERT INTO `command` VALUES ('go trigger', '4', 'Syntax: .go trigger $trigger_id\\n teleported you to the Areatrigger with ID $trigger_id. The character will be teleported to the aim of the trigger if the außgewahlte Areatrigger Teleporttrigger is a. \');');
INSERT INTO `command` VALUES ('go xyz', '2', 'Syntax: .go xyz #X #y #Z [ #mapid [ #orientation \\n teleported to the point the player with the coordinates ( #X, #y, #z) of the map with the Ausrichtigung #mapid #orientation. If Z is not specified, the player is on the ground (or the water surface) teleported. If $mapid (or #orientation) is missing, the current map (or orientation) is kept. \');');
INSERT INTO `command` VALUES ('go zonexy', '2', 'Syntax: .go zonexy $x $y $zone] \\n teleport the player to the point with the Client-Koordinaten ( $x, $y) to the ground (or water) of the map $ZONEID or the current map, if $ZONEID was not specified. You can with the command .lookup search the zone area. \');');
INSERT INTO `command` VALUES ('go', '1', 'Syntax: .go $subcommand\\n .go for a list of subcommands or .help for info on the go $subcommand subcommand. \');');
INSERT INTO `command` VALUES ('gobject activate', '4', 'Syntax: .gobject activate $GUID\\n activates a Gameobject, such as a door or a button. \');');
INSERT INTO `command` VALUES ('gobject add', '4', 'Syntax: .gobject add $id <spawntimeSecs> \\n adds a Gameobject gameobject_template $id from your current position in the world. \\N spawntimesecs sets, this is optional the Spawnzeit. \\n Note: This is a copy of the .gameobject. \');');
INSERT INTO `command` VALUES ('gobject delete', '4', 'Syntax: .gobject delete $go_guid\\n The Gameobject removed with the GUID $go_guid. \');');
INSERT INTO `command` VALUES ('gobject move', '4', 'Syntax: .gobject move $goguid [ $x $y $z \\n move the Gameobject $goguid to the coordinates of the character (or to the coordinates ( $x, $y, $z), if these are given) . \');');
INSERT INTO `command` VALUES ('gobject near', '4', 'Syntax: .gobject near [ $distance\\\" \\n shows Gameobjects $distance from player in the distance. Shows Gameobjects guids and coordinates sorted by the distance from the character. If $distance was not specified, it is used as a default value 4. \');');
INSERT INTO `command` VALUES ('gobject set phase', '4', 'Syntax: .gobject set phase $GUID $phasemask\\n sets the stage for the Gameobject with ID $guid on $phasemask. The change is saved in the database. \');');
INSERT INTO `command` VALUES ('gobject target', '4', 'Syntax: .gobject target go_name_part] $go_id| $ \\n feel the nearest Gameobject and show its position. If $go_id or $go_name_part what specified, it will be the nearest Gameobject gamobject_template id $go_id with or with the specified part of the name $go_name detected and displayed. \');');
INSERT INTO `command` VALUES ('gobject add temp', '4', 'Syntax: .gobject add temp $id\\n adds a temporary Gameobject gameobject_template $id from a, not in the DB is saved. \');');
INSERT INTO `command` VALUES ('gobject turn', '4', 'Syntax: .gobject turn $goguid\\n sets the direction for the Gameobject $goguid currently looks like your character. \');');
INSERT INTO `command` VALUES ('gobject', '4', 'Syntax: .gobject $subcommand\\n .go for a list of subcommands or .help gobject $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('summon', '1', 'Syntax: .summon $charactername teleport\\n The Zielcharakter to you. The CHAR may be offline. \');');
INSERT INTO `command` VALUES ('gps', '1', 'Syntax: .GPS\\n indicates the Positioninfo for the selected character or for the selected creature. The Positioninfo includes X, Y, Z, orientation, map id and zone ID\');');
INSERT INTO `command` VALUES ('groupsummon', '1', 'Syntax: .groupsummon $name\\n teleported the Zielcharakter and his group to you. Only chars, which are online, will be teleported. \');');
INSERT INTO `command` VALUES ('guid', '4', 'Syntax: .Guid\\n indicates the GUID of the selected character. \');');
INSERT INTO `command` VALUES ('guild create', '4', 'Syntax: .guild create $GuildLeaderName $GuildName\\n Creates a guild with the name $GuildName with the player by guild leaders only as $GuildLeaderName. \');');
INSERT INTO `command` VALUES ('guild delete', '4', 'Syntax: .guild delete $GuildName\\n deletes the guild with the name $GuildName. \');');
INSERT INTO `command` VALUES ('guild invite', '4', 'Syntax: .guild invite $CharacterName $GuildName\\n adds the player $CharacterName the guild $GuildName. \');');
INSERT INTO `command` VALUES ('guild rank', '4', 'Syntax: .guild rank $CharacterName $rank $CharacterName\\n the player receives are the rank $rank in the guild. \');');
INSERT INTO `command` VALUES ('guild uninvite', '4', 'Syntax: .guild uninvite $CharacterName\\n removes the player from the guild $CharacterName. \');');
INSERT INTO `command` VALUES ('guild', '2', 'Syntax: .guild $subcommand\\n .guild for a list of subcommands or .help guild $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('help', '1', '$command syntax: .help. \\N display help for command $command. If no $command has been specified will display all the commands available\');');
INSERT INTO `command` VALUES ('hidearea', '4', 'Syntax: .hidearea $areaid\\n Hides the region of $areaid for the selected character. If no character is selected, this region will be hidden for you. \');');
INSERT INTO `command` VALUES ('honor add', '4', 'Syntax: .honor add $amount\\n adds a certain number of honor (today) the selected player. \');');
INSERT INTO `command` VALUES ('honor add kill', '4', 'Syntax: .honor add kill\\n Adds the selected unit as one of today\'s PVP-kills (you get a Rassenoberhaupt or honor if this unit is a player) \');');
INSERT INTO `command` VALUES ('honor update', '4', 'Syntax: .honor update\\n forces the yesterday\'s Ehrenfeld with today\'s data to be renewed, however, today\'s data will be deleted for the selected player. \');');
INSERT INTO `command` VALUES ('honor', '4', 'Syntax: .honor $subcommand\\n .honor for a list of subcommands or .Help honor $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('modify talentpoints', '4', 'Syntax: .modify talentpoints #amount\\r\\n\\r\\nSet free talent points for selected character or character\\\'s pet. It will be reset to default expected at next center levelup/login/quest reward. \');');
INSERT INTO `command` VALUES ('instance listbinds', '4', 'Syntax: .instance lists the Instancenbindungen listbinds\\n of the selected player. \');');
INSERT INTO `command` VALUES ('instance savedata', '4', 'Syntax: .instance savedata\\n saves the InstanceData for the map of the current player in the DB \');');
INSERT INTO `command` VALUES ('instance stats', '4', 'Syntax: .instance stats\\n shows the statistics of the instances. \');');
INSERT INTO `command` VALUES ('instance unbind', '4', 'Syntax: .instance unbind <mapid|All \"difficulty] \\n all/only the specified Instancenbindungen of the selected player will be deleted. \" );');
INSERT INTO `command` VALUES ('instance', '4', 'Syntax: .instance $subcommand\\n .instance for a list of the subcommands or .help instance $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('itemmove', '4', 'Syntax: .itemmove $sourceslotid $destinationslotid\\n move an item from the slot to slot $destinationslotid $sourceslotid in your inventory. \');');
INSERT INTO `command` VALUES ('kick', '1', 'Syntax: .kick [ $charactername [ $reason] \\n kicks the entered character names from the world. With or without a reason. If no character name has been entered, then the selected player kicked. If no reason given was, is standard \\ \"NO\\ \" . \');');
INSERT INTO `command` VALUES ('learn all crafts', '4', 'Syntax: .learn all crafts\\n learns all occupations and recipes. \');');
INSERT INTO `command` VALUES ('learn all default', '4', 'Syntax: .learn all default [ $playername] \\n learns for the selected/ $playername Standardzauber players all his race/class and charm, which he completed quest got. \');');
INSERT INTO `command` VALUES ('learn all gm', '4', 'Syntax: .learn all GM\\n Learn all the spells for a gamemaster. \');');
INSERT INTO `command` VALUES ('learn all lang', '4', 'Syntax: .learn all long\\n Learn all languages. \');');
INSERT INTO `command` VALUES ('learn all my class', '4', 'Syntax: .learn all my class\\n Learn All spells and talents for the class are available. \');');
INSERT INTO `command` VALUES ('learn all my pettalents', '4', 'Syntax: .learn all my pettalents\\n learns all the talent for the currently active PET for this type are available. (Only for hunters pets) \');');
INSERT INTO `command` VALUES ('learn all my spells', '4', 'Syntax: .learn all my spells\\n Learn All spells (except for the talents and the magic that the first tier of talent is learned), for the class are available. \');');
INSERT INTO `command` VALUES ('learn all my talents', '4', 'Syntax: .learn all my talent\\n learns all the talent (and magic of which the first tier of talent is learned), for the class are available. \');');
INSERT INTO `command` VALUES ('learn all recipes', '4', 'Syntax: .learn all recipes [ $profession. \\n teaches you all of the recipes a special profession and requires the ability to the maximum. \\n example: .learn all_recipes an enchanting\');');
INSERT INTO `command` VALUES ('levelup', '4', 'Syntax: .center levelup [ $playername] $numberoflevels] \\n increases/decreases the level of the player with $playername (or of the selected player if no name has been specified) to $numberoflevels or +1, if no $numberoflevels was specified).  If $numberoflevels is 0, the same level of begin again. If no character has been selected and no name has been specified, your level is changed. The command can be used for characters that are offline. All statistics and attributes are calculated again. If the level has been reduced can be reset the talents. You can also scale items with a higher level will be lost, if the level is lowered. \');');
INSERT INTO `command` VALUES ('linkgrave', '4', 'Syntax: .linkgrave $graveyard_id [alliance|horde] \\n sets the current area as Friedhofsregion for all (or for alliance|horde).  Thus Charaktergeister always be brought to the nearest cemetery after they died, if the cemetery of the next is accepted and the spirit of this group. Only add a single cemetery to another map and only if no cemetery is verlingt. \');');
INSERT INTO `command` VALUES ('list auras', '4', 'Syntax: .list auras\\n indicates the active auras of the selected chars or your, if no Char is selected. \');');
INSERT INTO `command` VALUES ('list creature', '4', 'Syntax: .list creature $creature_id [ $ ###MAX_COUNT###] \\n shows creatures with ID $creature_id, were found in the world. Displays the guids of the creature and the Koordianten, these are listed after the distance to the character. There will be a maximum of $ ###MAX_COUNT### is issued. If $ ###MAX_COUNT### was not specified will be used as a default value the value 4. \');');
INSERT INTO `command` VALUES ('list item', '4', 'Syntax: .list item $item_id [ $ ###MAX_COUNT###] \\n indicates the items with ID $item_id, the inventory, the Post Office, the auctions or the guilds all players were found. Shows the Itemguids, Besitzerguids Besitzeraccount the items, and Owner name (Gildenname and GUID if Gildenbank).  There is a maximum of $ ###MAX_COUNT### items. If $ ###MAX_COUNT### was not specified will be used as a default value 4. \');');
INSERT INTO `command` VALUES ('list object', '4', 'Syntax: .list object $gameobject_id [ $ ###MAX_COUNT###] \\n shows Gameobjects with ID $gameobject_id, were found in the world. Shows the Gameobjects with guids and coordinates, sorted by the distance to the character. There is a maximum of $ ###MAX_COUNT### Gameobjects. If $ ###MAX_COUNT### was not specified we 4 used as a default value. \');');
INSERT INTO `command` VALUES ('list', '4', 'Syntax: .list $subcommand\\n .list for a list of subcommands or .help list $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('listfreeze', '1', 'Syntax: .listfreeze\\n lists all the time by .freeze frozen player. \');');
INSERT INTO `command` VALUES ('wp reload', '4', 'Syntax: .wp reload $pathid\\n loads changes on the way ingame. - Important -: must be used for new ways it is essential, before .path load $pathid may be used. \');');
INSERT INTO `command` VALUES ('reload spell_group', '4', 'Syntax: .reload Reload spell_group spell_group\\n table. \');');
INSERT INTO `command` VALUES ('lookup area', '2', 'Syntax: .lookup area $namepart\\n is looking for an area with $namepart, and all the results with their area IDs. \');');
INSERT INTO `command` VALUES ('lookup creature', '4', 'Syntax: .lookup creature $namepart\\n searches for a NPC with $namepart, and there are all found with your identity. \');');
INSERT INTO `command` VALUES ('lookup event', '2', 'Syntax: .lookup Event $name\\n is looking for an event with the specified name $name. \');');
INSERT INTO `command` VALUES ('lookup faction', '2', 'Syntax: .lookup faction $name\\n is looking for the group with the specified name $name. \');');
INSERT INTO `command` VALUES ('lookup item', '1', 'Syntax: .lookup item $itemname\\n is looking for a item with $itemname, and there are all found with your Item ID. \');');
INSERT INTO `command` VALUES ('lookup itemset', '4', 'Syntax: .lookup itemset $itemname\\n is looking for a Itemset namepart, and all with $found with Your item ID. \');');
INSERT INTO `command` VALUES ('lookup map', '4', 'Syntax: .lookup map $namepart\\n is looking for a map with $namepart, and returns all results with their map IDs from. \');');
INSERT INTO `command` VALUES ('lookup object', '2', 'Syntax: .lookup object $OBJNAME\\n searches for a Gameobject with $namepart, and are all found with your Gameobject ID\');');
INSERT INTO `command` VALUES ('lookup player account', '1', 'Syntax: .lookup player account $account ( $limit) \\n looks for players that have the specified accountname $account. With the optional parameter $limit can be limited the number of results. \');');
INSERT INTO `command` VALUES ('lookup player email', '4', 'Syntax: .lookup player email $email ( $limit) \\n looking for player whose specified Accountemail $is email. With the optional parameter $limit can be limited the number of results. \');');
INSERT INTO `command` VALUES ('lookup player ip', '1', 'Syntax: .lookup player ip $IP ( $limit) \\n lists all of the players, the last with the IP $IP were logged in. With the optional parameter $limit can be limited the number of results. \');');
INSERT INTO `command` VALUES ('lookup quest', '1', 'Syntax: .lookup quest $namepart\\n searches for a quest with $namepart, and are all found with your quest ID. \');');
INSERT INTO `command` VALUES ('lookup skill', '4', 'Syntax: .lookup skill $namepart\\n searches for a skill with $namepart, and are all found with their skill ID. \');');
INSERT INTO `command` VALUES ('lookup spell', '4', 'Syntax: .lookup spell $namepart\\n searches for a spell (spell) with $namepart, and are all found with your Spell ID. \');');
INSERT INTO `command` VALUES ('lookup taxinode', '4', 'Syntax: .lookup taxinode $substring searches for and returns all\\n Flugmeister/marinas, the $substring in the name. \');');
INSERT INTO `command` VALUES ('lookup tele', '1', 'Syntax: .lookup tele $substring searches for and returns all\\n .tele areas, the $substring in their names, from. \');');
INSERT INTO `command` VALUES ('lookup', '1', 'Syntax: .lookup $subcommand\\n .lookup for a list of subcommands or .help lookup $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('maxskill', '4', 'syntax: .Maxskill\\n sets all skills of the selected player at their maximum value for its current level. \');');
INSERT INTO `command` VALUES ('modify speed walk', '1', 'Syntax: .modify speed bwalk #rate\\r\\n\\r\\nModify the speed of the selected player while running to \\ \"normal walk speed\\\" * rate. If no player is selected, modify your speed. \\r\\n\\r\\n #rate may range from 0.1 to 60. \');');
INSERT INTO `command` VALUES ('modify bit', '4', 'Syntax: .modify bit $field $bit\\n changes the $bit bit of the field $field for the selected player. If no player is selected, your character will be modified. \');');
INSERT INTO `command` VALUES ('modify speed swim', '4', 'Syntax: .modify speed swim #rate\\r\\n\\r\\nModify the swim speed of the selected player to \\ \"normal swim speed\\\" * rate. If no player is selected, modify your speed. \\r\\n\\r\\n #rate may range from 0.1 to 60. \');');
INSERT INTO `command` VALUES ('modify drunk', '2', 'Syntax: .modify drunk $value\\n sets the Betrunkenheitszustand on $value (0.. 100).  A value of 0 removes the drunkeness, 100 is the highest Betrunkenheitszustand. \');');
INSERT INTO `command` VALUES ('modify energy', '4', 'Syntax: .modify energy $energy\\n changes the energy of the selected player. If no player is selected, will be your energy. \');');
INSERT INTO `command` VALUES ('modify faction', '2', 'Syntax: .modify faction $factionid $flagid $npcflagid $dynamicflagid\\n changes the group and flag of the selected creature. Without arguments, the Group and flag of the selected creature. \');');
INSERT INTO `command` VALUES ('modify speed fly', '1', '.modify speed fly #rate\\nModify the flying speed of the selected player to \\ \"normal flying speed\\\" * rate. If no player is selected, modify your speed. \\n #rate may range from 0.1 to 60. \');');
INSERT INTO `command` VALUES ('modify gender', '4', 'Syntax: .modify gender male/female\\n changes the sex of the selected player. \');');
INSERT INTO `command` VALUES ('modify honor', '3', 'Syntax: .modify honor $amount\\n Adds the number of $amount to Ehrenpunkten the selected player. \');');
INSERT INTO `command` VALUES ('modify hp', '4', 'Syntax: .modify hp $newhp\\n changes the HP of the selected player. If no player is selected, your HP changed. \');');
INSERT INTO `command` VALUES ('modify mana', '4', 'Syntax: .modify mana $newmana\\n changes the mana of the selected player. If no player is selected, your Mana changed. \');');
INSERT INTO `command` VALUES ('modify money', '4', 'Syntax: .modify money $money\\n Adds the selected player money $money to the Bronze or takes him this money. If no player is selected, your money is modified. \');');
INSERT INTO `command` VALUES ('modify mount', '4', 'Syntax: .modify mount $id $speed\\n shows the selected player on the creature as aufgemounted with $id and sets the speed to the value of $speed. \');');
INSERT INTO `command` VALUES ('modify phase', '4', 'Syntax: .modify phase $phasemask\\n changes the phase of the selected player on the phase $phasemask and the adjusts the view of the player. The change will remain active until the phase change in the game or the next GM-mode on/off or the next relog plastics will be showing. \');');
INSERT INTO `command` VALUES ('modify rage', '4', 'Syntax: .modify rage $newrage\\n changes the rage (range) of the selected player. If no player is selected, your anger. \');');
INSERT INTO `command` VALUES ('modify reputation', '4', 'Syntax: .modify reputation #adifferent repId attribute ( #repvalue | $rankname [ #delta] ) \\nSets the selected player reputation with faction #adifferent repId attribute to #repvalue or to $reprank. \\nIf the reputation rank name is provided, the resulting reputation will be the lowest reputation for that rank plus the delta amount, if specified. \\nYou can use \\ \' .pinfo rep\\\' to list all known reputation ids, or use \\ \' .lookup faction $name\\\' to locate a specific faction id. \');');
INSERT INTO `command` VALUES ('modify runicpower', '4', 'Syntax: .modify runicpower $newrunicpower\\n changes the rune power that enables him - (runicpower) of the selected player. If no player is selected, will be your rune power that enables him - amended. \');');
INSERT INTO `command` VALUES ('modify speed', '1', 'Syntax: .modify speed $rate\\n changes the speed running a selected player from \\\"Normalgeschwindigkeit\\\" * rate. If no player is selected, will be your speed changed. \\n $rate may range from 0.1 to 50. \');');
INSERT INTO `command` VALUES ('modify spell', '4', 'Syntax: .modify spell\\n todo. \');');
INSERT INTO `command` VALUES ('modify standstate', '4', 'Syntax: .modify standstate $emoteid\\n changes the emote of the selected chars on $emoteid if he is. \');');
INSERT INTO `command` VALUES ('modify speed backwalk', '4', 'Syntax: .modify speed backwalk #rate\\r\\n\\r\\nModify the speed of the selected player while running backwards to \\ \"normal walk back speed\\\" * rate. If no player is selected, modify your speed. \\r\\n\\r\\n #rate may range from 0.1 to 60. \');');
INSERT INTO `command` VALUES ('character titles', '4', 'Syntax: .character titles ( $name) \\n Displays the list of known title for the selected char or Char $name. \');');
INSERT INTO `command` VALUES ('modify speed all', '4', 'Syntax: .modify aspeed #rate\\r\\n\\r\\nModify all speeds -run,swim,run back,swim back- of the selected player to \\ \"normalbase type\\\" * rate speed for this move. If no player is selected, modify your speed. \\r\\n\\r\\n #rate may range from 0.1 to 60. \');');
INSERT INTO `command` VALUES ('modify', '1', 'Syntax: .modify $subcommand\\n .modify for a list of subcommands or .help modify $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('movegens', '4', 'Syntax: .movegens Bewegungsgeneratoren\\n Displays a list of the for the selected target creature or the selected player. \');');
INSERT INTO `command` VALUES ('mute', '1', 'Syntax: .mute $playerName $timeInMinutes\\n disabled the chat messages for each character of the accounts of the character $playerName for $timeInMinutes minutes. \');');
INSERT INTO `command` VALUES ('nameannounce', '1', 'Syntax: .nameannounce $MessageToBroadcast\\n sends a notification to all the players in the chat window and displays the name of the transmitter to. \');');
INSERT INTO `command` VALUES ('appear', '1', 'Syntax: .appear [ $name you teleported to the selected \\n char or Char $name. The CHAR may be offline. \');');
INSERT INTO `command` VALUES ('neargrave', '1', 'Syntax: .neargrave [alliance|horde] \\n finds the next cemetery of the zone is connected to the current (or only the next of the alliance or Hordegeister accepts) . \');');
INSERT INTO `command` VALUES ('notify', '1', 'Syntax: .notify $MessageToBroadcast\\n sends a Systemnachticht to all players who are online, click the screen. \');');
INSERT INTO `command` VALUES ('npc set allowmove', '4', 'Syntax: .NPC set allowmove\\n Enables or disables the Movement for the selected creature. Not yet implemented. \');');
INSERT INTO `command` VALUES ('npc set entry', '4', 'Syntax: .NPC set entry $entry\\n change the template of the NPC to $entry. The change is not stored in the DB. \');');
INSERT INTO `command` VALUES ('npc set level', '4', 'Syntax: .NPC set level $level\\n sets the level of the selected creature to $level. \\n $level has a valid value from 1 to 63. \');');
INSERT INTO `command` VALUES ('npc delete', '4', 'Syntax: .NPC delete [ $Guid. \\n deletes the NPC with the GUID $GUID (or the selected, if no GUID was specified) \');');
INSERT INTO `command` VALUES ('npc delete item', '4', 'Syntax: .NPC delete item $Itemid\\n removes the item from the list of the selected $Itemid seller. \');');
INSERT INTO `command` VALUES ('npc set factionid', '4', 'Syntax: .NPC set factionid $factionid\\n Set the Group of the selected creature to $factionid. \');');
INSERT INTO `command` VALUES ('npc set flag', '4', 'Syntax: .NPC set flag $npcflag\\n Set the NPC-flag of the selected creature creature_template and the selected creature to $npcflag. The NPC-flag is all creatures of the chosen creature_template only after a server restart or a grid unload/load effect. \');');
INSERT INTO `command` VALUES ('npc follow', '4', 'Syntax: .NPC follow\\n softpatch creature begins to follow you until death/fight/etc. \');');
INSERT INTO `command` VALUES ('npc follow stop', '4', 'Syntax: .NPC follow stop\\n softpatch creature (not companion) will stop you to follow. \');');
INSERT INTO `command` VALUES ('npc info', '1', 'Syntax: .NPC info\\n Displays a list of details of the selected creature. \\n The list includes: \\n - GUID, fraction, NPC flag, Entry ID, Model ID, \\n - level, \\n - Life (current/maximum) , \\n - Field flags, dynamic flags, faction tempalte, \\n - location information, \\n - and the creature type, for example, if a seller is the creature. \');');
INSERT INTO `command` VALUES ('npc move', '4', 'Syntax: .NPC move $creature_guid] \\n move the spawn point of the currently selected creature to your coordinates. \');');
INSERT INTO `command` VALUES ('npc playemote', '4', 'Syntax: .NPC playemote $emoteid\\n  The selected creature with an emote run A Emote ID $emoteid. \');');
INSERT INTO `command` VALUES ('npc say', '4', 'Syntax: .NPC say $message\\n the selected creature say the message $message. \');');
INSERT INTO `command` VALUES ('wpgps', '4', 'Syntax: .wpgps drezeitige\\n There are SQL Developer position in the log as a SQL query, is used for pathing. \');');
INSERT INTO `command` VALUES ('npc set link', '4', 'Syntax: .NPC set link $creatureGUID\\n links the Respawn of the selected NPC to NPC $creatureGUID. The selected NPC will only respawns, if $creatureGUID lives\');');
INSERT INTO `command` VALUES ('npc set model', '4', 'Syntax: .NPC set model $displayid\\n change the appearance of the selected creature to $displayid. \');');
INSERT INTO `command` VALUES ('npc set movetype', '4', 'Syntax: .NPC set movetype [ $creature_guid] stay/random/way [Nodel] \\n sets for the specified by $creature_guid creature (or for the selected, if $creature_guid not specified was) movement type and sets you on your Respawnpostion back (if the creature lives).  All existing waypoints for this creature will be deleted from the database, if not Nodel has been used. If the creature is dead, the motion with the Kreaturrespawn active. \\n Do not forget Nodel, if you want to keep the waypoints. \');');
INSERT INTO `command` VALUES ('npc set phase', '4', 'Syntax: .NPC set phase $phasemask\\n changes the phase of the selected NPCs on the phase $phasemask. The change is saved in the database. \');');
INSERT INTO `command` VALUES ('npc set spawndist', '4', 'Syntax: .NPC set spawndist $dist\\n changes the Spawndistanz the selected creature to $dist. \');');
INSERT INTO `command` VALUES ('npc set spawntime', '4', 'Syntax: .NPC set spawntime $time \\n changes the respawn very quick of the selected creature to $time. \');');
INSERT INTO `command` VALUES ('npc add temp', '4', 'Syntax: .NPC add temp $id\\n adds a temporary NPC with the with the $creatureid from creature_template. Is not stored in the DB. \');');
INSERT INTO `command` VALUES ('npc textemote', '4', 'Syntax: .NPC textemote $emoteid\\n the selected creature the Textemote with the emote with ID $emoteid run. \');');
INSERT INTO `command` VALUES ('npc whisper', '4', 'Syntax: .NPC whisper $playerguid $text\\n of the selected NPC whispers the text $text the player $playerguid. \');');
INSERT INTO `command` VALUES ('npc yell', '4', 'Syntax: .NPC yell $message\\n the selected creature the message $message cry out. \');');
INSERT INTO `command` VALUES ('server set loglevel', '4', 'Syntax: .server set loglevel $level\\n sets Server Log Level (0 - Errors only, 1 - Standard, 2 - Detailed, 3 - Debug) . \');');
INSERT INTO `command` VALUES ('server shutdown', '4', 'Syntax: .server shutdown #seconds #Message #Message optional] \\r\\n\\r\\nthe server is shut down after #seconds indication. Optionally, you can use the player as a source #Message. \');');
INSERT INTO `command` VALUES ('pdump load', '4', 'Syntax: .pdump load $filename $account [ $newname [ $referred to as newguid in] \\n loads character dump in Charakterliste of $account with saved or in $newname the given name, with stored (or first free) or in $referred to as newguid in specified Guid. \');');
INSERT INTO `command` VALUES ('pdump write', '4', 'Syntax: .pdump write $filename $playerNameOrGUID\\n memory a Charakter-Dump the chars with name/guid $playerNameOrGUID in a file with the name $filename. \');');
INSERT INTO `command` VALUES ('pdump', '4', 'Syntax: .pdump $subcommand\\n .pdump for a list of subcommands or .help pdump $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('pet create', '4', 'Syntax: .pet create\\n makes the selected tier to your Pet. \');');
INSERT INTO `command` VALUES ('pet learn', '4', 'Syntax: .pet learn $spellid\\n brings the Pet the magic $spellid. \');');
INSERT INTO `command` VALUES ('reload spell_proc', '4', 'Syntax: .reload Reload spell_proc spell_proc\\n table. \');');
INSERT INTO `command` VALUES ('pet unlearn', '4', 'Syntax: .pet unlearn $spellid\\n the Pet forgotten the magic $Spellid. \');');
INSERT INTO `command` VALUES ('pet', '4', 'Syntax: .pet $subcommand\\n .pet  For a list of subcommands or .help pet $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('playall', '4', 'Syntax: .playall $soundid\\n games the sound with ID $soundid for the whole server. \');');
INSERT INTO `command` VALUES ('possess', '4', 'Syntax: .possess\\n assumes control of the selected NPC. \');');
INSERT INTO `command` VALUES ('quest add', '1', 'Syntax: .quest add $quest_id\\n adds the character in its Quest-Log the Quest $quest_id. Quests are started by items can not be added by this command, however, .additem command as provided for this purpose. \');');
INSERT INTO `command` VALUES ('quest complete', '1', 'Syntax: .quest complete $questid\\n closes the Quest $questid. After this command, you can make the goal the quests and the reward. \');');
INSERT INTO `command` VALUES ('quest remove', '1', 'Syntax: .quest remove $quest_id\\n removes the Quest $quest_id from the Quest-Log of the selected player. \');');
INSERT INTO `command` VALUES ('quest', '2', 'Syntax: .quest $subcommand\\n .quest for a list of subcommands or .help quest $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('recall', '1', 'Syntax: .recall [ $playername. \\n teleported $playername or the selected player to the place where he was before the last teleport-command. If no $playername has been entered, or no player has been selected, you will be teleported. \');');
INSERT INTO `command` VALUES ('reload all scripts', '4', 'Syntax: .reload all scripts\\n loads the scripts tables (gameobject_scripts, event_scripts, quest_end_scripts, quest_start_scripts, spell_scripts, db_script_string, waypoint_scripts tables. ) \');');
INSERT INTO `command` VALUES ('reload all quest', '4', 'Syntax: .reload all quest\\n invites all tables, with the related quests, reload support and can be recharged safely. \');');
INSERT INTO `command` VALUES ('reload all npc', '4', 'Syntax: .reload all NPC\\n invites all NPC related tables (npc_option, npc_trainer, npc_vendor, points of interest) . \');');
INSERT INTO `command` VALUES ('reload all loot', '4', 'Syntax: .reload all\\n invites all * _loot_template loot tables. This can take a long time and cause lag on the server. \');');
INSERT INTO `command` VALUES ('reload all locales', '4', 'Syntax: .reload all locales\\n invites all locales_ * tables (translations) . \');');
INSERT INTO `command` VALUES ('reload all item', '4', 'Syntax: .reload all item\\n invites all item related tables (page_text, item_enchantment_table) . \');');
INSERT INTO `command` VALUES ('reload areatrigger_involvedrelation', '4', 'Syntax: .reload Reload areatrigger_involvedrelation areatrigger_involvedrelation\\n table. \');');
INSERT INTO `command` VALUES ('reload areatrigger_tavern', '4', 'Syntax: .reload Reload areatrigger_tavern areatrigger_tavern\\n table. \');');
INSERT INTO `command` VALUES ('reload areatrigger_teleport', '4', 'Syntax: .reload Reload areatrigger_teleport areatrigger_teleport\\n table. \');');
INSERT INTO `command` VALUES ('reload autobroadcast', '4', 'Syntax: .reload Reload autobroadcast autobroadcast\\n table. \');');
INSERT INTO `command` VALUES ('reload command', '4', 'Syntax: .reload command\\n Reload command Table. \');');
INSERT INTO `command` VALUES ('reload config', '4', 'Syntax: .reload config\\n Loads the settings of the Config (by default in the trinityd.conf to find).  Not all settings can be changed with a reload: some new values will be ignored until the system restarts, other values can be changed with delay or you will be only applied to new objects/maps, other values are changed completely until the next reboot. \');');
INSERT INTO `command` VALUES ('reload creature_involvedrelation', '4', 'Syntax: .reload Reload creature_involvedrelation creature_involvedrelation\\n table. \');');
INSERT INTO `command` VALUES ('reload creature_linked_respawn', '4', 'Syntax: .reload Reload creature_linked_respawn creature_linked_respawn\\n table. \');');
INSERT INTO `command` VALUES ('reload creature_loot_template', '4', 'Syntax: .reload Reload creature_loot_template creature_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload creature_questrelation', '4', 'Syntax: .reload Reload creature_questrelation creature_questrelation\\n table. \');');
INSERT INTO `command` VALUES ('reload disenchant_loot_template', '4', 'Syntax: .reload Reload disenchant_loot_template disenchant_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload event_scripts', '4', 'Syntax: .reload Reload event_scripts event_scripts\\n table. \');');
INSERT INTO `command` VALUES ('reload fishing_loot_template', '4', 'Syntax: .reload Reload fishing_loot_template fishing_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload game_graveyard_zone', '4', 'Syntax: .reload Reload game_graveyard_zone game_graveyard_zone\\n table. \');');
INSERT INTO `command` VALUES ('reload game_tele', '4', 'Syntax: .reload Reload game_tele game_tele\\n table. \');');
INSERT INTO `command` VALUES ('reload gameobject_involvedrelation', '4', 'Syntax: .reload Reload gameobject_involvedrelation gameobject_involvedrelation\\n table. \');');
INSERT INTO `command` VALUES ('reload gameobject_loot_template', '4', 'Syntax: .reload Reload gameobject_loot_template gameobject_loot_template\\n  Table. \');');
INSERT INTO `command` VALUES ('reload gameobject_questrelation', '4', 'Syntax: .reload Reload gameobject_questrelation gameobject_questrelation\\n table. \');');
INSERT INTO `command` VALUES ('reload gm_tickets', '4', 'Syntax: .reload Reload gm_tickets gm_tickets\\n table. \');');
INSERT INTO `command` VALUES ('reload item_enchantment_template', '4', 'syntax: .Reload Reload item_enchantment_template item_enchantment_template\\n table. \');');
INSERT INTO `command` VALUES ('reload item_loot_template', '4', 'Syntax: .reload Reload item_loot_template item_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload locales_creature', '4', 'Syntax: .reload Reload locales_creature locales_creature\\n table. \');');
INSERT INTO `command` VALUES ('reload locales_gameobject', '4', 'Syntax: .reload Reload locales_gameobject locales_gameobject\\n table. \');');
INSERT INTO `command` VALUES ('reload locales_item', '4', 'Syntax: .reload Reload locales_item locales_item\\n table. \');');
INSERT INTO `command` VALUES ('reload locales_npc_text', '4', 'Syntax: .reload Reload locales_npc_text locales_npc_text\\n table. \');');
INSERT INTO `command` VALUES ('reload locales_page_text', '4', 'Syntax: .reload Reload locales_page_text locales_page_text\\n table. \');');
INSERT INTO `command` VALUES ('reload locales_points_of_interest', '4', 'Syntax: .reload Reload locales_point_of_interest locales_points_of_interest\\n table. \');');
INSERT INTO `command` VALUES ('reload locales_quest', '4', 'Syntax: .reload Reload locales_quest locales_quest\\n table. \');');
INSERT INTO `command` VALUES ('reload milling_loot_template', '4', 'Syntax: .reload Reload milling_loot_template milling_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload npc_trainer', '4', 'Syntax: .reload Reload npc_trainer npc_trainer\\n table. \');');
INSERT INTO `command` VALUES ('reload npc_vendor', '4', 'Syntax: .reload Reload npc_vendor npc_vendor\\n table. \');');
INSERT INTO `command` VALUES ('reload page_text', '4', 'Syntax: .reload Reload page_text page_text\\n table. \');');
INSERT INTO `command` VALUES ('reload pickpocketing_loot_template', '4', 'Syntax: .reload Reload pickpocketing_loot_template pickpocketing_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload points_of_interest', '4', 'Syntax: .reload points_of_interest \\N Reload points_of_interest Table. \');');
INSERT INTO `command` VALUES ('reload prospecting_loot_template', '4', 'Syntax: .reload Reload prospecting_loot_template prospecting_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload mail_loot_template', '4', 'Syntax: .reload Reload mail_loot_template mail_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload quest_template', '4', 'Syntax: .reload Reload quest_template quest_template\\n table. \');');
INSERT INTO `command` VALUES ('reload reference_loot_template', '4', 'Syntax: .reload Reload reference_loot_template reference_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload reserved_name', '4', 'Syntax: .reload Reload reserved_name reserved_name\\n table. \');');
INSERT INTO `command` VALUES ('reload skill_discovery_template', '4', 'syntax: .Reload Reload skill_discovery_template skill_discovery_template\\n table. \');');
INSERT INTO `command` VALUES ('reload skill_extra_item_template', '4', 'Syntax: .reload Reload skill_extra_item_template skill_extra_item_template\\n table. \');');
INSERT INTO `command` VALUES ('reload skill_fishing_base_level', '4', 'Syntax: .reload Reload skill_fishing_base_level skill_fishing_base_level\\n table. \');');
INSERT INTO `command` VALUES ('reload skinning_loot_template', '4', 'Syntax: .reload Reload skinning_loot_template skinning_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_area', '4', 'Syntax: .reload Reload spell_area spell_area\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_bonus_data', '4', 'Syntax: .reload Reload spell_bonus_data spell_bonus_data\\n table. \');');
INSERT INTO `command` VALUES ('reload disables', '4', 'Syntax: .reload Reload disables disables\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_group_stack_rules', '4', 'Syntax: .reload Reload spell_group_stack_rules spell_group_stack_rules\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_learn_spell', '4', 'Syntax: .reload Reload spell_learn_spell spell_learn_spell\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_linked_spell', '4', 'Syntax: .reload Reload spell_linked_spell spell_linked_spell\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_loot_template', '4', 'Syntax: .reload Reload spell_loot_template spell_loot_template\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_pet_auras', '4', 'Syntax: .reload Reload spell_pet_auras spell_pet_auras\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_proc_event', '4', 'Syntax: .reload Reload spell_proc_event spell_proc_event\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_required', '4', 'Syntax: .reload Reload spell_required spell_required\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_scripts', '4', 'Syntax: .reload spell_scripts \\N Reload spell_scripts Table. \');');
INSERT INTO `command` VALUES ('reload spell_target_position', '4', 'Syntax: .reload Reload spell_target_position spell_target_position\\n table. \');');
INSERT INTO `command` VALUES ('reload spell_threats', '4', 'Syntax: .reload Reload spell_threats spell_threats\\n table. \');');
INSERT INTO `command` VALUES ('reload trinity_string', '4', 'Syntax: .reload Reload trinity_string trinity_string\\n table. \');');
INSERT INTO `command` VALUES ('reload waypoint_scripts', '4', 'Syntax: .reload Reload waypoint_scripts waypoint_scripts\\n table. \');');
INSERT INTO `command` VALUES ('reload', '4', 'Syntax: .reload $subcommand\\n .reload for a list The subcommands or .help reload $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('repairitems', '3', 'Syntax: .repairitems\\n repaired all objects of the selected player. \');');
INSERT INTO `command` VALUES ('reset achievements', '4', 'Syntax: .reset achievements [ $name \\n sets all the successes for the selected char or Char $name. Static successes (e.g. , number of completed quests, number of mounts etc. ) are recalculated and restored at the next login, successes for events (kills etc) are lost. \');');
INSERT INTO `command` VALUES ('reset all', '4', 'Syntax: .reset all spells\\nusage: .reset all talent\\nSetzt and, be aware, _all_ the spells or talents for existing characters on the next login. \');');
INSERT INTO `command` VALUES ('reset honor', '4', 'Syntax: .reset honor [ $name \\n sets all the data, the honor, for the selected char or Char $name back (0) . \');');
INSERT INTO `command` VALUES ('reset level', '4', 'Syntax: .reset level [ $name \\n sets for the selected char or Char $name the level to 1, this also includes the stats and talents. Scale items with a higher level may be lost. \');');
INSERT INTO `command` VALUES ('reset spells', '4', 'Syntax: .reset spells ( $name) \\n Removes all spells (magic) from the magic for the selected char or Char $name (can also be offline) . \\n\');');
INSERT INTO `command` VALUES ('reset stats', '4', 'Syntax: .reset stats ( $name) \\n sets(calculated new) All Stats of the selected player or the player\'s name to the original values of the $current levels. \');');
INSERT INTO `command` VALUES ('reset talents', '4', 'Syntax: .reset talents ( $name) \\n away all the talent of the selected player, of the selected pets or the player\'s $name (can also be offline) . \');');
INSERT INTO `command` VALUES ('reset', '4', 'Syntax: .reset $subcommand\\n .reset for a list of subcommands or .help reset $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('respawn', '2', 'Syntax: .respawn immediately respawned\\n the selected NPC or NPCs, and all go in the near (if none is selected) . \');');
INSERT INTO `command` VALUES ('revive', '1', 'Syntax: .revive\\n enlivens the selected player. If no player has been selected, you will be revived. \');');
INSERT INTO `command` VALUES ('save', '1', 'Syntax: .Save\\n saves your character. \');');
INSERT INTO `command` VALUES ('saveall', '2', 'Syntax: .saveall\\n stores all characters in the game. \');');
INSERT INTO `command` VALUES ('send items', '4', 'Syntax: .send items $playername \\ \" $subject\\\" \\ \" $text\\\" Itemid1 [ :count1] Itemid2 [ :count2... itemidN[ :countN] \\n sends the items by e-mail to a player. Subject and the text of the mail must be in \\ \" \\\" be specified. If no Itemanzahl for the ItemID is specified, a value of 1 for example, if the number > Max stack, the items sent in a number of places. All of the seats in a Mail are limited to 4. \');');
INSERT INTO `command` VALUES ('send mail', '2', 'Syntax: .send mail $playername \\ \" $subject\\\" \\ \" $text\\ \" \\n sends a mail to a player. Subject and the text of the mail must be in \\ \" \\\" be specified. \');');
INSERT INTO `command` VALUES ('send message', '2', 'Syntax: .send message $playername $message\\n sends $playername you should receive $message to players of administrator. \');');
INSERT INTO `command` VALUES ('send money', '4', 'Syntax: .send money $playername \\ \" $subject\\\" \\ \" $text\\\" $money\\n sends money to a player. Subject and the text of the mail must be in \\ \" \\\" be specified. \');');
INSERT INTO `command` VALUES ('server corpses', '4', 'Syntax: .server\\n Lost corpses that had been laid expire check corpses that had been laid in the world. \');');
INSERT INTO `command` VALUES ('server exit', '4', 'Syntax: .server exit\\n finished trinityd immediately. \');');
INSERT INTO `command` VALUES ('server idlerestart cancel', '4', 'Syntax: .server idlerestart cancel\\n stops the Restart/Shutdown Countdown. \');');
INSERT INTO `command` VALUES ('server idlerestart', '4', 'Syntax: .server idlerestart $delay|cancel\\n starts the server to $delay seconds, if there are no active connections (no players) . \');');
INSERT INTO `command` VALUES ('server idleshutdown cancel', '4', 'Syntax: .server idleshutdown cancel\\n stops the Restart/Shutdown Countdown. \');');
INSERT INTO `command` VALUES ('server idleshutdown', '4', 'Syntax: .server idleshutdown $delay|cancel\\n driving down the server to $delay seconds, if there are no active connections (no players) . \');');
INSERT INTO `command` VALUES ('server info', '4', 'Syntax: .server info\\n indicates the server version and the number of logged-in player. \');');
INSERT INTO `command` VALUES ('server motd', '4', 'Syntax: .server motd\\n indicates the message of the day. \" );');
INSERT INTO `command` VALUES ('server plimit', '4', 'Syntax: .server Plimit [ $num  | -1 | -2 | -3 |reset|Player|moderator|gamemaster|administrator. \\n Set the current limits for the Login. \\n $num > 0: Sets the maximum permissible Number; $num < 0 or Level Name: only players with at least the specified GM-level can login. \\n reset resets the values to the setting in the cfg-file. \\n No argument: Displays the currently set limits. \');');
INSERT INTO `command` VALUES ('server restart cancel', '4', 'Syntax: .server restart cancel\\n stops the Restart/Shutdown Countdown. \');');
INSERT INTO `command` VALUES ('server restart', '4', 'Syntax: .server restart $seconds|cancel\\n start the server after the expiration of $seconds Seconds and re-displays regularly until then \\ \"Server restart in x\\ \" . \');');
INSERT INTO `command` VALUES ('server set closed', '4', 'Syntax: .server set closed on/off\\n with On/Off Determines whether the server to accept new Client Connections. \');');
INSERT INTO `command` VALUES ('server set motd', '4', 'Syntax: .server set motd $MOTD\\n changes the message of the day on $motd. \');');
INSERT INTO `command` VALUES ('server shutdown cancel', '4', 'Syntax: .server shutdown cancel\\n stops the Restart/Shutdown Countdown. \');');
INSERT INTO `command` VALUES ('server', '4', 'Syntax: .server $subcommand\\n .server for a list of subcommands or .help server $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('setskill', '3', 'Syntax: .setskill $skill $level [ $max\" \\n sets a Skill Id $skill with a correct Skillwert $level and a maximum value of $max (or similar Correct Maximum value if this is not specified) for the Selected character. If no character is selected, you will learn the Skill. \');');
INSERT INTO `command` VALUES ('showarea', '4', 'Syntax: .showarea $areaid\\n covers the territory with $areaid for the selected character. If no character is selected, this field will be uncovered for you. \');');
INSERT INTO `command` VALUES ('unstuck', '3', 'Syntax: .unstuck $playername [inn/graveyard/zone. \\n\\nTeleports specified player to specified location. Default location is player\\\'s current hearth location. \');');
INSERT INTO `command` VALUES ('cheat god', '4', 'Syntax: .cheat god on/off] \\r\\nEnables or disables your character\\\'s ability to take damage. \');');
INSERT INTO `command` VALUES ('cheat casttime', '4', 'Syntax: .cheat casttime on/off \\r\\nEnables or disables your character\\\'s spell cast times. \');');
INSERT INTO `command` VALUES ('tele add', '2', 'Syntax: .tele add $name\\n adds the current position to the .tele command list with the name $name. \');');
INSERT INTO `command` VALUES ('tele del', '4', 'Syntax: .tele del $name\\n removes the field with the name $name of the .tele command list. \');');
INSERT INTO `command` VALUES ('tele group', '2', 'Syntax: .tele group $location\\n teleported a selected player and his group members to the specified field $location. \');');
INSERT INTO `command` VALUES ('tele name', '1', 'Syntax: .tele name $playername $location\\n teleported to the player $playername gegebebenen area the $location. \');');
INSERT INTO `command` VALUES ('tele', '1', 'Syntax: .tele $location\\n\\n the selected player teleported to the specified area; the player may be offline. If no player is selected the own Char teleported\\n to the player to teleport to his home town as a place \\ \" $HOME\\\" (without the \\ \" ) . \');');
INSERT INTO `command` VALUES ('ticket assign', '1', 'Syntax: .ticket assign $ticket ID $gmname. \\n the Ticket, $ticket ID to the gamemasters $gmname. \');');
INSERT INTO `command` VALUES ('ticket close', '1', 'Syntax: .ticket close $ticket ID. \\n closes the ticket $ticket ID. The Ticket will not permanently deleted. To delete: \\ \" .ticket delete\\ \" \');');
INSERT INTO `command` VALUES ('ticket closedlist', '1', 'Syntax: .ticket closedlist\\n shows the list of gamemasters closed tickets. \');');
INSERT INTO `command` VALUES ('ticket comment', '1', 'Syntax: .ticket comment $ticket ID $comment. \\n allows you to add or change a previous reviewer for the Ticket, $ticket ID $comment. \');');
INSERT INTO `command` VALUES ('ticket delete', '1', 'Syntax: .ticket delete $ticket ID. \\n deletes the Ticket $ticket ID final. The ticket must be closed ( \\ \" .ticket close\\ \" ) . \');');
INSERT INTO `command` VALUES ('ticket list', '1', 'Syntax: .ticket list\\n shows the list of all open GM Tickets. \');');
INSERT INTO `command` VALUES ('ticket onlinelist', '1', 'Syntax: .ticket onlinelist\\n shows the list of open GM ticket, whose author is online. \');');
INSERT INTO `command` VALUES ('ticket unassign', '1', 'Syntax: .ticket unassign $ticket ID. \\n solves the Ticket, $ticket ID assigned by gamemasters. \');');
INSERT INTO `command` VALUES ('ticket viewid', '1', 'Syntax: .ticket viewid $ticket ID. \\n shows the ticket $ticket-ID. Ticket must be open, and must not be deleted. \');');
INSERT INTO `command` VALUES ('ticket viewname', '1', 'Syntax: .ticket viewname $creatorname. \\n shows the tickets from author $creatorname. Ticket must be open, and must not be deleted. \');');
INSERT INTO `command` VALUES ('ticket', '1', 'Syntax: .ticket $subcommand\\n .ticket for a list of subcommands or .help ticket $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('unaura', '2', 'Syntax: .unaura $spellid\\n removes the Aura will be caused by the spell $spellid on the selected unit. \');');
INSERT INTO `command` VALUES ('unban account', '2', 'Syntax: .unban removes account $name\\n raises the spell of all accounts on the pattern match $name. \');');
INSERT INTO `command` VALUES ('unban character', '4', 'Syntax: .unban removes character $name\\n raises the spell of all accounts for which the fit on the search pattern $name. \');');
INSERT INTO `command` VALUES ('unban ip', '4', 'Syntax: .unban removes ip $IP\\n raises the spell for the IP $ip. \');');
INSERT INTO `command` VALUES ('unban', '2', 'Syntax: .unban removes $subcommand\\n .unban removes for a list of subcommands or .help unban removes $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('unbindsight', '3', 'Syntax: .unbindsight\\n removes the associated view. Cannot be used while your controlled another destination. \');');
INSERT INTO `command` VALUES ('unfreeze', '1', 'Syntax: .unfreeze [ $playername] \\n the selected char or Char $name is released again and be unlocked Chat. \');');
INSERT INTO `command` VALUES ('unlearn', '4', 'Syntax: .unlearn $spell all \\n the selected player forgotten how the magic $spell. With the name \\ \"All\\\" are all range from $spell forgotten. \');');
INSERT INTO `command` VALUES ('unmute', '1', 'Syntax: .unmute [ $playername] \\n The chat will be for the account of the selected player or the player\'s $playername released again. The player may be offline. \');');
INSERT INTO `command` VALUES ('unpossess', '4', 'Syntax: .unpossess\\n If you are in control, you will raise your the Fremdkontrolle. Otherwise it is heartening to an NPC to your control. \');');
INSERT INTO `command` VALUES ('cheat', '4', 'Syntax: .cheat $subcommand\\r\\ntype .cheat to see the list of possible subcommands or .help cheat $subcommand to see info on subcommands\');');
INSERT INTO `command` VALUES ('wchange', '4', 'Syntax: .wchange $weathertype $status\\n changes the weather to $weathertype with an intensity of $status. \\n $weathertype: 1 for rain, 2 for snow, 3 for sand. $Status: 0 for disabled, 1 for Enabled. \');');
INSERT INTO `command` VALUES ('whispers', '1', 'Syntax: .whispers on|off\\n allowed (on) or prohibits (off) normal players send private message to you. By default, the information of trinityd.conf is used. \');');
INSERT INTO `command` VALUES ('wp event', '4', 'Syntax: .wp event $subcommand\\n .path for a list of subcommands or .help path event $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('wp load', '4', 'Syntax: .wp load $pathid\\n loads the way $pathid for the selected NPC. The NPC may not route data. \');');
INSERT INTO `command` VALUES ('wp show', '4', 'Syntax: .wp show $option options: \\n\\n on $pathid - displays debug output (visible Waypoints) for the way $pathid or the selected Char (if this route data) . \\n off - hides the path again. \\n info - Displays more detailed information about the currently selected visible waypoint. \');');
INSERT INTO `command` VALUES ('wp unload', '4', 'Syntax: .wp unload\\n away the way of the selected NPC. \');');
INSERT INTO `command` VALUES ('account addon', '4', 'Syntax: .account addon $addon\\n Set the allowed extensions for this account. Allowed values: 0 - normal 1 - The Burning Crusade, 2 - Wrath of the Lich King\');');
INSERT INTO `command` VALUES ('titles remove', '4', 'Syntax: .titles remove. \\n deletes the title with ID $titleid or with shift-click generated link of a title from the list of possible title of the selected character. \');');
INSERT INTO `command` VALUES ('titles current', '4', 'Syntax: .titles current. \\n sets the title with ID $titleid or with shift-click a title link generated as active title for the selected character. If the character doesn\'t know the title, he will add his list. \');');
INSERT INTO `command` VALUES ('titles add', '4', 'Syntax: .titles add $titleid. \\n adds the title with ID $titleid or with shift-click a title link generated the list of the possible title of the selected character. \');');
INSERT INTO `command` VALUES ('titles set mask', '4', 'Syntax: .titles set mask $mask. \\n allows the selected character all title in accordance with the (bit- )mask $mask to use. \\n $mask=0 disables the Titelauswahlfeld. \');');
INSERT INTO `command` VALUES ('lookup title', '2', 'Syntax: .lookup title $substring\\n searches for and returns all titles including your ID from, the $substring in the name. \');');
INSERT INTO `command` VALUES ('channel set ownership', '4', 'Syntax: .channel set ownership $channel on/off] \\n On: The channel is one of the person who was the first channel accession. \');');
INSERT INTO `command` VALUES ('gobject info', '3', 'Syntax: .gobject info $object_entry] \\n query of the Gameobject information for the selected object or the entry $object_entry. \');');
INSERT INTO `command` VALUES ('reload creature_template', '4', 'Syntax: .reload creature_template $entry\\ N loads the template For the NPC $entry. \');');
INSERT INTO `command` VALUES ('character deleted delete', '4', 'Syntax: .character deleted delete $guid| $name\\n the selected chars will be permanently deleted. \\n If you specify $name will be deleted, only the chars in the name contain the $name. \\n If you specify $GUID will be deleted only the Char with that GUID. \');');
INSERT INTO `command` VALUES ('reload conditions', '4', 'Syntax: .reload conditions\\n Reload conditions Table. \');');
INSERT INTO `command` VALUES ('character deleted list', '4', 'Syntax: .character deleted list $guid| $name \\n list of deleted but recoverable chars. \\n If you specify $name will be displayed only the chars, the $name in the name. \\n If you specify $GUID will be displayed only the Char with that GUID. \');');
INSERT INTO `command` VALUES ('character deleted old', '4', 'Syntax: .character deleted old [ $keepdays] \\n all chars, the days before at least $keepdays have been deleted, will be permanently deleted. \\n without indication of the value from the $keepdays worldserver.conf. \');');
INSERT INTO `command` VALUES ('character deleted restore', '4', 'Syntax: .character deleted restore $GUID| $name $newname] [ $Newaccount. \\n restores deleted chars. \\n If you specify $name will be restored only the chars, the $name in the name. \\n If you specify $GUID is only the Char with that GUID restored. \\n If you specify $newname is renamed by the Char. If you specify $account will be restored to this account instead of on the original account. \\n $newname and $account can only be used, if only one Char has been selected. \');');
INSERT INTO `command` VALUES ('reload gossip_menu', '4', 'Syntax: .reload Reload gossip_menu gossip_menu\\n table. \');');
INSERT INTO `command` VALUES ('reload gossip_menu_option', '4', 'Syntax: .reload Reload gossip_menu_option gossip_menu_option\\n table. \');');
INSERT INTO `command` VALUES ('reload all gossips', '4', 'Syntax: .reload all gossips\\n Reloading gossip_menu, gossip_menu_option, gossip_scripts, points_of_interest tables. \');');
INSERT INTO `command` VALUES ('reload locales_gossip_menu_option', '4', 'Syntax: .reload Reload locales_gossip_menu_option locales_gossip_menu_option\\n table. \');');
INSERT INTO `command` VALUES ('reload quest_poi', '4', 'Syntax: .reload Reload quest_poi quest_poi\\n table. \');');
INSERT INTO `command` VALUES ('reload lfg_dungeon_rewards', '4', 'Syntax: .reload Reload lfg_dungeon_rewards lfg_dungeon_rewards\\n table. \');');
INSERT INTO `command` VALUES ('character changerace', '4', 'Syntax: .character changerace $name\\n changes the race of the specified chars. \');');
INSERT INTO `command` VALUES ('character changefaction', '4', 'Syntax: .character changefaction $name\\n changes the fraction of the specified chars. \');');
INSERT INTO `command` VALUES ('ban playeraccount', '4', 'Syntax: .ban playeraccount $name $bantime $reason\\reqapt for additional time account and kick player. \\n$bantime: negative value leads to permban, otherwise Use a timestring like \\ \" 5D20h3s\\ \' . \');');
INSERT INTO `command` VALUES ('achievement add', '4', 'Syntax: .achievement add $achievement\\n indicates the success of the selected player. \\n  $Achievement: success either as an ID or as a link. \');');
INSERT INTO `command` VALUES ('achievement', '4', 'Syntax: .achievement $subcommand\\n .achievement for a list of subcommands or .help achievement $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('reload creature_text', '4', 'Syntax: .reload Reload creature_text creature_text\\n table. \');');
INSERT INTO `command` VALUES ('debug areatriggers', '4', 'Syntax: .debug areatriggers\\n sets the debug mode for areatrigger on/off. In debug mode, it will a GM notified whenever he reached a areatrigger. \');');
INSERT INTO `command` VALUES ('modify scale', '3', 'Syntax: .modify scale $size\\n changes the size of the selected player. If no player is selected, will be your size changed. \\n $size can range from 0.1 to 4. \');');
INSERT INTO `command` VALUES ('learn', '4', 'Syntax: .learn $parameters\\n of the selected character learns the magic (spell) with ID $parameters. \');');
INSERT INTO `command` VALUES ('npc add move', '4', 'Syntax: .NPC add move $creature_guid [ $waittime] \\n adds the current location as a waypoint with the waiting time $waittime NPC with the GUID $creature_guid. \');');
INSERT INTO `command` VALUES ('npc add item', '4', 'Syntax: .NPC add item $Itemid < $maxcount> < $incrtime> < $extendedcost> \\n adds the item $Itemid to sales lists of the selected vendor. You can also optionally, the maximum number of items that may be sold, the time until this be refilled and extended cost (ExtendedCost) be specified. \');');
INSERT INTO `command` VALUES ('npc add formation', '4', 'Syntax: .NPC add formation $leader\\n Adds the selected NPC of the formation of the group leader $leader. \');');
INSERT INTO `command` VALUES ('npc add', '4', 'Syntax: .NPC add $creatureid\\n Spawnt a creature with the given template id of $creatureid. \');');
INSERT INTO `command` VALUES ('npc', '2', 'Syntax: .NPC $subcommand\\n .NPC for a list of subcommands or .help NPC $subcommand for info on the subcommand. \');');
INSERT INTO `command` VALUES ('reload all', '4', 'Syntax: .reload all\\n invites all tables, and to make sure the reload support can be recharged. \');');
INSERT INTO `command` VALUES ('wp add', '4', 'Syntax: .wp add\\n adds the current location as a waypoint the selected NPC. \');');
INSERT INTO `command` VALUES ('reload all spell', '4', 'Syntax: .reload all spell\\n invites all spell_ * tables, and to make sure the reload support can be recharged. \');');
INSERT INTO `command` VALUES ('reload access_requirement', '4', 'syntax: .Reload Reload access_requirement access_requirement\\n table. \');');
INSERT INTO `command` VALUES ('reload achievement_criteria_data', '4', 'Syntax: .reload Reload achievement_criteria_data achievement_criteria_data\\n table. \');');
INSERT INTO `command` VALUES ('reload achievement_reward', '4', 'Syntax: .reload Reload achievement_reward achievement_reward\\n table. \');');
INSERT INTO `command` VALUES ('reload all achievement', '4', 'Syntax: .reload all achievement\\r\\n\\r\\nReload achievement_reward, achievement_criteria_data tables. \');');
INSERT INTO `command` VALUES ('reload all area', '4', 'Syntax: .reload all area\\r\\n\\r\\nReload areatrigger_teleport, areatrigger_tavern, game_graveyard_zone tables. \');');
INSERT INTO `command` VALUES ('reload auctions', '4', 'Syntax: .reload auctions\\n Reload dynamic data table. \');');
INSERT INTO `command` VALUES ('reload mail_level_reward', '4', 'Syntax: .reload Reload mail_level_reward mail_level_reward\\n table. \');');
INSERT INTO `command` VALUES ('reload smart_scripts', '4', 'Syntax: .reload Reload smart_scripts smart_scripts\\n table. \');');
INSERT INTO `command` VALUES ('reload vehicle_accessory', '4', 'Syntax: .reload Reload vehicle_accessory vehicle_accessory\\n table. \');');
INSERT INTO `command` VALUES ('pinfo', '1', 'Syntax: .pinfo [ $player_name/ #GUID. \\n There is account information for the selected player or the player with $player_name or #GUID is found. \');');
INSERT INTO `command` VALUES ('reload vehicle_template_accessory', '4', 'Syntax: .reload Reload vehicle_template_accessory vehicle_template_accessory\\n table. \');');
INSERT INTO `command` VALUES ('unban playeraccount', '2', 'Syntax: .unban removes Playeraccount $name\');');
INSERT INTO `command` VALUES ('cast dest', '4', 'Syntax: .cast dest $spellid $x $y $z [triggered] \\n the selected target applies the magic $spellid on the specified point. If \\ \'trigered\\\' or only a part is specified, then the spell will worked with triggered flag. \');');
INSERT INTO `command` VALUES ('dev', '4', 'Syntax: .dev on/off \\n indicates the current value of the \\ \"Dev tags\\\" ( Entwicklungs-Markierung ) or turns it on/off. \');');
INSERT INTO `command` VALUES ('ticket reset', '4', 'Syntax: .ticket reset\\n deletes all closed tickets and sets the Ticketzahler back, if no more tickets are open. \');');
INSERT INTO `command` VALUES ('debug moveflags', '4', 'Syntax: .debug moveflags [ $newMoveFlags [ $newMoveFlags2] \\r\\NNE params given wants to output the current moveflags of the target\');');
INSERT INTO `command` VALUES ('reload locales_creature_text', '4', 'Syntax: .reload locales_creature_text\\nReload locales_creature_text Table. \');');
INSERT INTO `command` VALUES ('morph', '1', 'Syntax: .morph #displayid\\r\\n\\r\\nChange selected your current model id to #displayid. \');');
INSERT INTO `command` VALUES ('npc set data', '4', 'Syntax: .NPC set data $field $data\\r\\nSets data for the selected creature. Used for testing Scripting\');');
INSERT INTO `command` VALUES ('disable add quest', '4', 'Syntax: .disable add quest $entry $flag $comment\');');
INSERT INTO `command` VALUES ('disable add map', '4', 'Syntax: .disable add map $entry $flag $comment\');');
INSERT INTO `command` VALUES ('disable add battleground', '4', 'Syntax: .disable add battleground $entry $flag $comment\');');
INSERT INTO `command` VALUES ('disable add achievement_criteria', '4', 'Syntax: .disable add achievement_criteria $entry $flag $comment\');');
INSERT INTO `command` VALUES ('disable add spell', '4', 'Syntax: .disable add spell $entry $flag $comment\');');
INSERT INTO `command` VALUES ('disable add outdoorpvp', '4', 'Syntax: .disable add outdoorpvp $entry $flag $comment\');');
INSERT INTO `command` VALUES ('disable add vmap', '4', 'Syntax: .disable add VMAP $entry $flag $comment\');');
INSERT INTO `command` VALUES ('disable remove quest', '4', 'Syntax: .disable remove quest $entry\');');
INSERT INTO `command` VALUES ('disable remove map', '4', 'Syntax: .disable remove map $entry\');');
INSERT INTO `command` VALUES ('disable remove battleground', '4', 'Syntax: .disable remove battleground $entry\');');
INSERT INTO `command` VALUES ('disable remove achievement_criteria', '4', 'Syntax: .disable remove achievement_criteria $entry\');');
INSERT INTO `command` VALUES ('disable remove spell', '4', 'Syntax: .disable remove spell $entry\');');
INSERT INTO `command` VALUES ('disable remove outdoorpvp', '4', 'Syntax: .disable remove outdoorpvp $entry\');');
INSERT INTO `command` VALUES ('disable remove vmap', '4', 'Syntax: .disable remove VMAP $entry\');');
INSERT INTO `command` VALUES ('bf switch', '4', 'Syntax: .bf switch #battleid\');');
INSERT INTO `command` VALUES ('bf enable', '4', 'Syntax: .bf enable #battleid\');');
INSERT INTO `command` VALUES ('bf stop', '4', 'Syntax: .bf stop #battleid\');');
INSERT INTO `command` VALUES ('bf start', '4', 'Syntax: .bf start #battleid\');');
INSERT INTO `command` VALUES ('quest reward', '2', 'Syntax: .quest reward #questId\\n\\nGrants quest reward to selected player and removes from his quest log (quest  Must be in Completed state) . \');');
INSERT INTO `command` VALUES ('bf timer', '4', 'Syntax: .bf timer #battleid #timer\');');
INSERT INTO `command` VALUES ('cheat waterwalk', '4', 'Syntax: .cheat waterwalk on/off on/off\\r\\nSet waterwalk state for selected player or self if no player selected. \');');
INSERT INTO `command` VALUES ('cheat explore', '4', 'Syntax: .cheat explore #flag\\r\\nReveal or hide all maps for the selected player. If no player is selected, hide or reveal maps to you. \\r\\nUse a #flag of value 1 to reveal, use a #flag value of 0 to hide all maps. \');');
INSERT INTO `command` VALUES ('cheat taxi', '4', 'Syntax: .cheat taxi on/off\\r\\nTemporary grant access or remove to all taxi routes for the selected character. \\r\\n If no character is selected, hide or reveal all routes to you.visited taxi nodes sill accessible after removing access. \');');
INSERT INTO `command` VALUES ('cheat status', '4', 'Syntax: .cheat status \\n\\nShows the cheats you currently have enabled. \');');
INSERT INTO `command` VALUES ('verwarnungen', '0', 'Syntax: .warnings - displays the warnings of an account of\');');
INSERT INTO `command` VALUES ('verwarnen', '1', 'Syntax: .warn $character name $reason\');');
INSERT INTO `command` VALUES ('strafen', '0', 'Syntax: .penalties - shows the penalties of an account of\');');
INSERT INTO `command` VALUES ('strafe', '1', 'Syntax: . $penalty points penalty $character name $reason\');');
INSERT INTO `command` VALUES ('delstrafe', '4', 'Syntax: .delstrafe $StrafID\');');
INSERT INTO `command` VALUES ('tempban', '4', 'Syntax: .tempban $Playername $reason\');');
INSERT INTO `command` VALUES ('deltempban', '4', 'Syntax: .deltempban $Playername\');');
