DELETE FROM creature_equip_template WHERE entry=2077;
INSERT INTO `creature_equip_template` VALUES ('2077', '1', '5292', '0', '0');
UPDATE creature_template SET equipment_id=0 WHERE entry=1988;
DELETE FROM creature_equip_template WHERE entry=1988;
UPDATE creature_template SET equipment_id=0 WHERE entry=1989;
DELETE FROM creature_equip_template WHERE entry=1989;
UPDATE creature_template SET equipment_id=0 WHERE entry=1986;
DELETE FROM creature_equip_template WHERE entry=1986;
UPDATE creature_template SET equipment_id=0 WHERE entry=1994;
DELETE FROM creature_equip_template WHERE entry=1994;
UPDATE creature_template SET equipment_id=0 WHERE entry=2082;
DELETE FROM creature_equip_template WHERE entry=2082;
DELETE FROM creature_equip_template WHERE entry=3592;
INSERT INTO `creature_equip_template` VALUES ('3592', '1', '1902', '0', '0');
UPDATE creature_template SET equipment_id=0 WHERE entry=3596;
DELETE FROM creature_equip_template WHERE entry=3596;
UPDATE creature_template SET equipment_id=0 WHERE entry=3591;
DELETE FROM creature_equip_template WHERE entry=3591;
UPDATE creature_template SET equipment_id=0 WHERE entry=3588;
DELETE FROM creature_equip_template WHERE entry=3588;
UPDATE creature_template SET equipment_id=0 WHERE entry=3590;
DELETE FROM creature_equip_template WHERE entry=3590;
DELETE FROM creature_equip_template WHERE entry=3597;
INSERT INTO `creature_equip_template` VALUES ('3597', '1', '5292', '0', '0');
UPDATE creature_template SET equipment_id=0 WHERE entry=3594;
DELETE FROM creature_equip_template WHERE entry=3594;
UPDATE creature_template SET equipment_id=0 WHERE entry=3593;
DELETE FROM creature_equip_template WHERE entry=3593;
UPDATE creature_template SET equipment_id=0 WHERE entry=3514;
DELETE FROM creature_equip_template WHERE entry=3514;
UPDATE creature_template SET equipment_id=0 WHERE entry=2008;
DELETE FROM creature_equip_template WHERE entry=2008;
UPDATE creature_template SET equipment_id=0 WHERE entry=7235;
DELETE FROM creature_equip_template WHERE entry=7235;
DELETE FROM creature_equip_template WHERE entry=4266;
INSERT INTO `creature_equip_template` VALUES ('4266', '1', '12856', '0', '0');
UPDATE creature_template SET equipment_id=0 WHERE entry=3608;
DELETE FROM creature_equip_template WHERE entry=3608;
UPDATE creature_template SET equipment_id=0 WHERE entry=3614;
DELETE FROM creature_equip_template WHERE entry=3614;
UPDATE creature_template SET equipment_id=0 WHERE entry=3613;
DELETE FROM creature_equip_template WHERE entry=3613;
UPDATE creature_template SET equipment_id=0 WHERE entry=3609;
DELETE FROM creature_equip_template WHERE entry=3609;
UPDATE creature_template SET equipment_id=0 WHERE entry=3612;
DELETE FROM creature_equip_template WHERE entry=3612;
UPDATE creature_template SET equipment_id=0 WHERE entry=3611;
DELETE FROM creature_equip_template WHERE entry=3611;
UPDATE creature_template SET equipment_id=0 WHERE entry=3306;
DELETE FROM creature_equip_template WHERE entry=3306;
UPDATE creature_template SET equipment_id=0 WHERE entry=3601;
DELETE FROM creature_equip_template WHERE entry=3301;
UPDATE creature_template SET equipment_id=0 WHERE entry=4265;
DELETE FROM creature_equip_template WHERE entry=4265;
UPDATE creature_template SET equipment_id=0 WHERE entry=3604;
DELETE FROM creature_equip_template WHERE entry=3604;
UPDATE creature_template SET equipment_id=0 WHERE entry=3515;
DELETE FROM creature_equip_template WHERE entry=3515;
UPDATE creature_template SET equipment_id=0 WHERE entry=2022;
DELETE FROM creature_equip_template WHERE entry=2022;
UPDATE creature_template SET equipment_id=0 WHERE entry=2080;
DELETE FROM creature_equip_template WHERE entry=2080;
UPDATE creature_template SET equipment_id=0 WHERE entry=1996;
DELETE FROM creature_equip_template WHERE entry=1996;
UPDATE creature_template SET equipment_id=0 WHERE entry=2010;
DELETE FROM creature_equip_template WHERE entry=2010;
UPDATE creature_template SET equipment_id=0 WHERE entry=2011;
DELETE FROM creature_equip_template WHERE entry=2011;
UPDATE creature_template SET equipment_id=0 WHERE entry=2025;
DELETE FROM creature_equip_template WHERE entry=2025;
UPDATE creature_template SET equipment_id=0 WHERE entry=2027;
DELETE FROM creature_equip_template WHERE entry=2027;
UPDATE creature_template SET equipment_id=0 WHERE entry=3535;
DELETE FROM creature_equip_template WHERE entry=3535;
UPDATE creature_template SET equipment_id=0 WHERE entry=1997;
DELETE FROM creature_equip_template WHERE entry=1997;
UPDATE creature_template SET equipment_id=0 WHERE entry=2017;
DELETE FROM creature_equip_template WHERE entry=2017;
UPDATE creature_template SET equipment_id=0 WHERE entry=2018;
DELETE FROM creature_equip_template WHERE entry=2018;
UPDATE creature_template SET equipment_id=0 WHERE entry=2015;
DELETE FROM creature_equip_template WHERE entry=2015;
UPDATE creature_template SET equipment_id=0 WHERE entry=2000;
DELETE FROM creature_equip_template WHERE entry=2000;
UPDATE creature_template SET equipment_id=0 WHERE entry=2020;
DELETE FROM creature_equip_template WHERE entry=2020;
UPDATE creature_template SET equipment_id=0 WHERE entry=2019;
DELETE FROM creature_equip_template WHERE entry=2019;
UPDATE creature_template SET equipment_id=0 WHERE entry=2021;
DELETE FROM creature_equip_template WHERE entry=2021;
UPDATE creature_template SET equipment_id=0 WHERE entry=2001;
DELETE FROM creature_equip_template WHERE entry=2001;
UPDATE creature_template SET equipment_id=0 WHERE entry=2030;
DELETE FROM creature_equip_template WHERE entry=2030;
UPDATE creature_template SET equipment_id=0 WHERE entry=2029;
DELETE FROM creature_equip_template WHERE entry=2029;
UPDATE creature_template SET equipment_id=0 WHERE entry=3605;
DELETE FROM creature_equip_template WHERE entry=3605;
UPDATE creature_template SET equipment_id=0 WHERE entry=4181;
DELETE FROM creature_equip_template WHERE entry=4181;
UPDATE creature_template SET equipment_id=0 WHERE entry=8665;
DELETE FROM creature_equip_template WHERE entry=8665;
DELETE FROM creature_equip_template WHERE entry=52641;
INSERT INTO `creature_equip_template` VALUES ('52641', '1', '12856', '0', '0');
UPDATE creature_template SET equipment_id=0 WHERE entry=4228;
DELETE FROM creature_equip_template WHERE entry=4228;
UPDATE creature_template SET equipment_id=0 WHERE entry=4730;
DELETE FROM creature_equip_template WHERE entry=4730;
UPDATE creature_template SET equipment_id=0 WHERE entry=4753;
DELETE FROM creature_equip_template WHERE entry=4753;
UPDATE creature_template SET equipment_id=0 WHERE entry=4219;
DELETE FROM creature_equip_template WHERE entry=4219;
UPDATE creature_template SET equipment_id=0 WHERE entry=4217;
DELETE FROM creature_equip_template WHERE entry=4217;
UPDATE creature_template SET equipment_id=0 WHERE entry=6142;
DELETE FROM creature_equip_template WHERE entry=6142;
UPDATE creature_template SET equipment_id=0 WHERE entry=4240;
DELETE FROM creature_equip_template WHERE entry=4240;
UPDATE creature_template SET equipment_id=0 WHERE entry=4155;
DELETE FROM creature_equip_template WHERE entry=4155;
UPDATE creature_template SET equipment_id=0 WHERE entry=4209;
DELETE FROM creature_equip_template WHERE entry=4209;
UPDATE creature_template SET equipment_id=0 WHERE entry=4208;
DELETE FROM creature_equip_template WHERE entry=4208;
UPDATE creature_template SET equipment_id=0 WHERE entry=6736;
DELETE FROM creature_equip_template WHERE entry=6736;
UPDATE creature_template SET equipment_id=0 WHERE entry=2002;
DELETE FROM creature_equip_template WHERE entry=2002;
UPDATE creature_template SET equipment_id=0 WHERE entry=2003;
DELETE FROM creature_equip_template WHERE entry=2003;
UPDATE creature_template SET equipment_id=0 WHERE entry=2162;
DELETE FROM creature_equip_template WHERE entry=2162;
DELETE FROM creature_equip_template WHERE entry=2007;
INSERT INTO `creature_equip_template` VALUES ('2007', '1', '3346', '0', '0');
UPDATE creature_template SET equipment_id=0 WHERE entry=2006;
DELETE FROM creature_equip_template WHERE entry=2006;
UPDATE creature_template SET equipment_id=0 WHERE entry=2009;
DELETE FROM creature_equip_template WHERE entry=2009;
UPDATE creature_template SET equipment_id=0 WHERE entry=2152;
DELETE FROM creature_equip_template WHERE entry=2152;
UPDATE creature_template SET equipment_id=0 WHERE entry=2039;
DELETE FROM creature_equip_template WHERE entry=2039;
UPDATE creature_template SET equipment_id=0 WHERE entry=1318;
DELETE FROM creature_equip_template WHERE entry=1318;
 
UPDATE creature_template SET equipment_id=0 WHERE entry=1317;
DELETE FROM creature_equip_template WHERE entry=1317;
DELETE FROM creature_equip_template WHERE entry=1339;
INSERT INTO `creature_equip_template` VALUES ('1339', '1', '1902', '0', '0');
UPDATE creature_template SET equipment_id=0 WHERE entry=1320;
DELETE FROM creature_equip_template WHERE entry=1320;
DELETE FROM creature_equip_template WHERE entry=1321;
INSERT INTO `creature_equip_template` VALUES ('1321', '1', '12854', '0', '0');
UPDATE creature_template SET equipment_id=0 WHERE entry=1315;
DELETE FROM creature_equip_template WHERE entry=1315;
UPDATE creature_template SET equipment_id=0 WHERE entry=1300;
DELETE FROM creature_equip_template WHERE entry=1300;
UPDATE creature_template SET equipment_id=0 WHERE entry=1346;
DELETE FROM creature_equip_template WHERE entry=1346;
UPDATE creature_template SET equipment_id=0 WHERE entry=1347;
DELETE FROM creature_equip_template WHERE entry=1347;
UPDATE creature_template SET equipment_id=0 WHERE entry=1314;
DELETE FROM creature_equip_template WHERE entry=1314;
UPDATE creature_template SET equipment_id=0 WHERE entry=3520;
DELETE FROM creature_equip_template WHERE entry=3520;
UPDATE creature_template SET equipment_id=0 WHERE entry=1299;
DELETE FROM creature_equip_template WHERE entry=1299;
UPDATE creature_template SET equipment_id=0 WHERE entry=1428;
DELETE FROM creature_equip_template WHERE entry=1428;
UPDATE creature_template SET equipment_id=0 WHERE entry=1304;
DELETE FROM creature_equip_template WHERE entry=1304;
UPDATE creature_template SET equipment_id=0 WHERE entry=1429;
DELETE FROM creature_equip_template WHERE entry=1429;
UPDATE creature_template SET equipment_id=0 WHERE entry=1309;
DELETE FROM creature_equip_template WHERE entry=1309;
UPDATE creature_template SET equipment_id=0 WHERE entry=1349;
DELETE FROM creature_equip_template WHERE entry=1349;
UPDATE creature_template SET equipment_id=0 WHERE entry=1350;
DELETE FROM creature_equip_template WHERE entry=1350;
UPDATE creature_template SET equipment_id=0 WHERE entry=1291;
DELETE FROM creature_equip_template WHERE entry=1291;
UPDATE creature_template SET equipment_id=0 WHERE entry=1295;
DELETE FROM creature_equip_template WHERE entry=1295;
UPDATE creature_template SET equipment_id=0 WHERE entry=1294;
DELETE FROM creature_equip_template WHERE entry=1294;
UPDATE creature_template SET equipment_id=0 WHERE entry=1721;
DELETE FROM creature_equip_template WHERE entry=1721;
UPDATE creature_template SET equipment_id=0 WHERE entry=3626;
DELETE FROM creature_equip_template WHERE entry=3626; 
UPDATE creature_template SET equipment_id=0 WHERE entry=3317;
DELETE FROM creature_equip_template WHERE entry=3317;
UPDATE creature_template SET equipment_id=0 WHERE entry=3364;
DELETE FROM creature_equip_template WHERE entry=3364;
DELETE FROM creature_equip_template WHERE entry=3363;
INSERT INTO `creature_equip_template` VALUES ('3363', '1', '1908', '0', '0');
DELETE FROM creature_equip_template WHERE entry=2855;
INSERT INTO `creature_equip_template` VALUES ('2855', '1', '0', '12745', '0');
UPDATE creature_template SET equipment_id=0 WHERE entry=3321;
DELETE FROM creature_equip_template WHERE entry=3321;
DELETE FROM creature_equip_template WHERE entry=5811;
INSERT INTO `creature_equip_template` VALUES ('5811', '1', '2184', '0', '0');
DELETE FROM creature_equip_template WHERE entry=3366;
INSERT INTO `creature_equip_template` VALUES ('3366', '1', '3699', '0', '0');
DELETE FROM creature_equip_template WHERE entry=44780;
INSERT INTO `creature_equip_template` VALUES ('44780', '1', '1910', '12870', '0');
UPDATE creature_template SET equipment_id=44779 WHERE entry=44779;
DELETE FROM creature_equip_template WHERE entry=44779;
INSERT INTO `creature_equip_template` VALUES ('44779', '1', '12854', '0', '0');
DELETE FROM creature_equip_template WHERE entry=16012;
INSERT INTO `creature_equip_template` VALUES ('16012', '1', '14824', '0', '0');
UPDATE creature_template SET equipment_id=0 WHERE entry=1383;
DELETE FROM creature_equip_template WHERE entry=1383;
DELETE FROM creature_equip_template WHERE entry=6929;
INSERT INTO `creature_equip_template` VALUES ('6929', '1', '6334', '0', '0'); 
INSERT INTO `creature_equip_template` VALUES ('3301', '1', '19987', '19987', '0');
