UPDATE `creature_template` SET `ScriptName`='npc_bloodfang_lurker' WHERE  `entry`=35463;
UPDATE `creature_template` SET `ScriptName`='npc_injured_soldier' WHERE  `entry`=50047;
UPDATE `creature_template` SET `ScriptName`='npc_krennan_aranas_c2' WHERE  `entry`=35753;
UPDATE `gameobject_template` SET `ScriptName`='go_mandragore' WHERE  `entry`=196394;
INSERT INTO `spell_script_names` (`spell_id` ,`ScriptName`) VALUES ('68735',  'spell_rescue_noyade');
UPDATE `creature_template` SET `ScriptName`='npc_worgen_warrior' WHERE  `entry`=38348;
UPDATE `creature_template` SET `ScriptName`='npc_prince_liam_greymane_gilneas' WHERE  `entry`=38218;
UPDATE `creature_template` SET `ScriptName`='npc_lady_sylvanas_gilneas' WHERE  `entry`=38469;
UPDATE `creature_template` SET `ScriptName`='npc_lorna_crowley_c2' WHERE  `entry`=38611;
UPDATE `creature_template` SET `ScriptName`='npc_chauve_souris_capture' WHERE  `entry`=38539;
UPDATE `creature_template` SET `ScriptName`='npc_tempest_storm' WHERE  `entry`=26045;
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES ('86930', 'spell_asaad_supremacy_entry');
UPDATE `creature_template` SET `ScriptName`='mob_skyfall_star' WHERE  `entry`=45932;
UPDATE `creature_template` SET `ScriptName`='mob_wild_vortex' WHERE  `entry`=45912;
UPDATE `creature_template` SET `ScriptName`='npc_bling_bling' WHERE  `entry`=35128;
UPDATE `creature_template` SET `ScriptName`='npc_bling_bling' WHERE  `entry`=35130;
UPDATE `creature_template` SET `ScriptName`='npc_bling_bling' WHERE  `entry`=35126;
UPDATE `creature_template` SET `ScriptName`='npc_singe_bombe' WHERE  `entry`=34699;
UPDATE `creature_template` SET `ScriptName`='npc_killag_sangrecroc' WHERE  `entry`=35917;
UPDATE `creature_template` SET `ScriptName`='npc_gyrocoptere_quest_giver' WHERE  `entry`=36127;
UPDATE `creature_template` SET `ScriptName`='npc_izzy_airplane' WHERE  `entry`=38928;
UPDATE `creature_template` SET `ScriptName`='npc_killag_2' WHERE  `entry`=39066;
UPDATE `creature_template` SET `ScriptName`='npc_grilly_2' WHERE  `entry`=38124;
UPDATE `creature_template` SET `ScriptName`='go_iron_rune_construct_workbank' WHERE  `entry`=24807;
UPDATE `creature_template` SET `ScriptName`='npc_lord_darius_crowley_gilneas' WHERE  `entry`=38415;
UPDATE `creature_template` SET `ScriptName`='npc_king_genn_greymane_c2' WHERE  `entry`=36332;
UPDATE `creature_template` SET `ScriptName`='npc_Proto_Drake_q11188' WHERE  `entry`=23689;
